[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "backend"
version = "0.1.0"
description = "Backend para la PoC2"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "pydantic",
    "uvicorn",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
    "ruff"
]

[tool.hatch.build.targets.wheel]
packages = ["src/app"]
