[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "senoide"
version = "0.1.0"
description = "PoC1: Script Python sencillo (señal senoidal)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "matplotlib",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mypy",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
# Hacemos que src sea parte del PYTHONPATH para los tests
pythonpath = ["src"]

[tool.ruff]
line-length = 100

[tool.mypy]
ignore_missing_imports = true

[project.scripts]
senoide = "senoide.cli:main"
